#!/usr/bin/env node
/**
 * scripts/e2e/scaffold-caller.mjs — caller/Action generation for the reusable
 * E2E pipeline (agent-ops issue #10, subtask 3c).
 *
 * Writes, into a target repo, the two files a brand-new repository needs to
 * adopt automated E2E testing with minimal configuration:
 *
 *   1. .github/workflows/e2e.yml   — a thin caller of e2e-pipeline-reusable.yml
 *   2. e2e-coverage.yaml           — the critical-flow manifest that
 *                                    check-flow-coverage.mjs enforces
 *
 * Both are built purely from detection output (detect.mjs) + an optional flow
 * list, so the same logic is unit-testable via `node --test` (renderCaller /
 * renderCoverageManifest are exported and side-effect free). The file writer
 * on top never clobbers an existing caller unless --force is passed — an
 * already-onboarded repo's committed workflow wins.
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, join, dirname } from 'node:path';

const DEFAULT_CONTROL_REPO = 'HeyItsChloe/agent-ops';

/**
 * Render the thin caller workflow YAML.
 * @param {object} opts
 * @param {object} opts.detection detect.mjs output
 * @param {string} [opts.controlRepo] owner/repo of the reusable-workflow host
 * @param {string} [opts.ref] git ref of the reusable workflow (default main)
 * @param {string} [opts.workingDirectory]
 * @param {boolean} [opts.autogen] enable the opt-in generate/repair mode
 * @returns {string}
 */
export function renderCaller({
  detection = {},
  controlRepo = DEFAULT_CONTROL_REPO,
  ref = 'main',
  workingDirectory = '.',
  autogen = false,
} = {}) {
  const needsEmulator = Boolean(detection.needsEmulator);
  const framework = detection.framework || 'unknown';
  const testFramework = detection.testFramework || 'playwright';
  const uses = `${controlRepo}/.github/workflows/e2e-pipeline-reusable.yml@${ref}`;

  const installCommand = defaultInstallCommand(detection);
  const testCommand = defaultTestCommand(detection);

  const withLines = [`      working_directory: ${yamlStr(workingDirectory)}`];

  if (autogen) {
    withLines.push(
      `      # Opt-in autogeneration + repair (agent-ops issue #10). The reusable`,
      `      # workflow detects, generates, installs, tests, and repairs.`,
      `      autogen: true`,
      `      test_framework: ${yamlStr(testFramework)}`,
      `      start_command: ${yamlStr(detection.startCommand || '')}`,
      `      base_url: ${yamlStr(detection.baseUrl || '')}`,
      `      max_repair_attempts: 3`,
    );
  } else {
    withLines.push(
      `      install_command: ${yamlStr(installCommand)}`,
      `      test_command: ${yamlStr(testCommand)}`,
    );
  }

  withLines.push(
    `      needs_emulator: ${needsEmulator}`,
    ...(needsEmulator ? [`      emulator_api_level: ${detection.emulatorApiLevel || 30}`] : []),
    `      record_video: \${{ inputs.record_video || false }}`,
    `      capture_screenshots: \${{ inputs.capture_screenshots || false }}`,
    `      coverage_manifest_path: e2e-coverage.yaml`,
    `      control_repo: ${yamlStr(controlRepo)}`,
  );

  return `# AUTO-GENERATED by scripts/e2e/scaffold-caller.mjs (agent-ops issue #10).
# Thin caller for ${controlRepo}'s reusable E2E pipeline.
# Detected: framework=${framework} testFramework=${testFramework} appType=${detection.appType || 'frontend'}.
# Safe to edit; re-running the scaffolder will not overwrite this without --force.

name: e2e

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      record_video:
        type: boolean
        default: false
      capture_screenshots:
        type: boolean
        default: false

jobs:
  e2e:
    permissions:
      contents: read
      pull-requests: write
    uses: ${uses}
    with:
${withLines.join('\n')}
`;
}

/**
 * Render the e2e-coverage.yaml manifest from a list of flow names.
 * @param {string[]} flows
 * @returns {string}
 */
export function renderCoverageManifest(flows = []) {
  const uniq = [...new Set(flows.filter(Boolean))];
  const body = uniq.length
    ? uniq.map((f) => `  - ${f}`).join('\n')
    : '  # - add-critical-flow-name-here';
  return `# AUTO-GENERATED by scripts/e2e/scaffold-caller.mjs (agent-ops issue #10).
# Critical user flows that must each have a matching PASSING test, enforced by
# scripts/check-flow-coverage.mjs. A flow is "covered" when its name appears as
# a substring of a passing test identifier (e.g. Playwright test('flow: <name>')).
flows:
${body}
`;
}

export function defaultInstallCommand(detection = {}) {
  if (detection.needsEmulator) return '';
  const pm = detection.packageManager || 'npm';
  const installBrowser =
    detection.testFramework === 'playwright'
      ? ' && npx playwright install chromium --with-deps'
      : '';
  switch (pm) {
    case 'yarn':
      return `yarn install --frozen-lockfile${installBrowser}`;
    case 'pnpm':
      return `pnpm install --frozen-lockfile${installBrowser}`;
    case 'bun':
      return `bun install${installBrowser}`;
    case 'pip':
      return 'pip install -r requirements.txt';
    default:
      return `npm ci${installBrowser}`;
  }
}

export function defaultTestCommand(detection = {}) {
  if (detection.needsEmulator) return './gradlew connectedDebugAndroidTest';
  switch (detection.testFramework) {
    case 'cypress':
      return 'npx cypress run';
    case 'jest':
      return 'npx jest';
    case 'mocha':
      return 'npx mocha';
    case 'playwright':
    default:
      return 'npx playwright test';
  }
}

function yamlStr(v) {
  const s = String(v ?? '');
  // Quote when it contains YAML-significant characters or is empty.
  if (s === '' || /[:#{}\[\],&*?|<>=!%@`"']/.test(s) || /^\s|\s$/.test(s)) {
    return JSON.stringify(s);
  }
  return s;
}

// ── File writer ──────────────────────────────────────────────────────────

function parseArgs(argv) {
  const args = { _: [] };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i].startsWith('--')) {
      const k = argv[i].slice(2);
      const v = argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[++i] : true;
      args[k] = v;
    } else {
      args._.push(argv[i]);
    }
  }
  return args;
}

function writeIfAbsent(path, content, force, label) {
  if (existsSync(path) && !force) {
    console.log(`[e2e-scaffold] ${label}: already exists — leaving as-is (use --force to overwrite).`);
    return false;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, 'utf8');
  console.log(`[e2e-scaffold] wrote ${label}.`);
  return true;
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const repoRoot = resolve(args['repo-root'] || '.');
  const detection = args.detection && existsSync(args.detection)
    ? JSON.parse(readFileSync(args.detection, 'utf8'))
    : {};
  const flows = args.flows && existsSync(args.flows)
    ? JSON.parse(readFileSync(args.flows, 'utf8'))
    : [];
  const controlRepo = args['control-repo'] || DEFAULT_CONTROL_REPO;
  const ref = args.ref || 'main';
  const workingDirectory = args['working-directory'] || '.';
  const autogen = Boolean(args.autogen);
  const force = Boolean(args.force);

  const caller = renderCaller({ detection, controlRepo, ref, workingDirectory, autogen });
  const manifest = renderCoverageManifest(Array.isArray(flows) ? flows : flows.flows || []);

  writeIfAbsent(join(repoRoot, '.github/workflows/e2e.yml'), caller, force, '.github/workflows/e2e.yml');
  writeIfAbsent(join(repoRoot, 'e2e-coverage.yaml'), manifest, force, 'e2e-coverage.yaml');
}

function isMain() {
  return process.argv[1] && process.argv[1].endsWith('scaffold-caller.mjs');
}

if (isMain()) {
  try {
    main();
  } catch (err) {
    console.error('[e2e-scaffold] FAILED:', err);
    process.exit(1);
  }
}
