// AUTO-GENERATED by scripts/wiki-generate.mjs - do not hand-edit.
// Source of truth is the adjacent .generated.json sidecar, which IS safe
// (and expected) to be hand-edited between generator runs - the merge
// logic in scripts/wiki-extractors/merge.mjs never overwrites or removes
// entries whose extracted source content has not changed.

import type { EndpointGroup } from '../types';
import data from './endpoints.generated.json';

export const endpointGroups = data as unknown as EndpointGroup[];

export function getGroup(slug: string) {
  return endpointGroups.find((g) => g.slug === slug);
}
